zap:
  level: "DEBUG"
  development: true
  disableCaller: false
  disableStacktrace: true
  encoding: "console"
  encoderConfig:
    messageKey: "msg"
    levelKey: "level"
    timeKey: "ts"
    nameKey: "name"
    callerKey: "caller"
    functionKey: "func"
    stacktraceKey: "stacktrace"
    lineEnding: "\n"
    timeEncoder: "iso8601"
    durationEncoder: "ms"
    callerEncoder: "full"
    nameEncoder: "full"
  outputPaths: ["stderr"]
  errorOutputPaths: ["stderr"]


db:
  driver: "mysql"
  uri: "root:root@tcp(127.0.0.1:3306)/chat_room?charset=utf8mb4"
  maxnums: 6
  idlenums: 5